export interface MaterialSummary {
  plywood: Record<string, number>;
  laminates: Record<string, number>;
  totalPlywoodSheets: number;
}

export function generateMaterialListCSV(materialSummary: MaterialSummary, clientName: string, roomName?: string): string {
  const lines: string[] = [];
  
  lines.push("Kitchen Cabinet Material List");
  lines.push("============================");
  lines.push("");
  
  if (clientName) {
    lines.push(`Project: ${clientName}`);
  }
  
  if (roomName) {
    lines.push(`Room: ${roomName}`);
  }
  
  const today = new Date().toISOString().split('T')[0];
  lines.push(`Date: ${today}`);
  lines.push("");
  lines.push("============================");
  lines.push("");
  
  // PLYWOOD SHEETS
  lines.push("PLYWOOD SHEETS");
  lines.push("-------------");
  lines.push(`Total: ${materialSummary.totalPlywoodSheets} sheets`);
  lines.push("");
  
  Object.entries(materialSummary.plywood)
    .sort(([, a], [, b]) => b - a)
    .forEach(([brand, count]) => {
      lines.push(`  ${brand}: ${count} sheets`);
    });
  lines.push("");
  
  // LAMINATE SHEETS
  if (Object.keys(materialSummary.laminates).length > 0) {
    const totalLaminates = Object.values(materialSummary.laminates).reduce((sum, count) => sum + count, 0);
    lines.push("LAMINATE SHEETS");
    lines.push("---------------");
    lines.push(`Total: ${totalLaminates} sheets`);
    lines.push("");
    Object.entries(materialSummary.laminates)
      .sort(([, a], [, b]) => b - a)
      .forEach(([code, count]) => {
        lines.push(`  ${code}: ${count} sheets`);
      });
    lines.push("");
  }
  
  lines.push("============================");
  lines.push("Generated by Maya Interiors Cabinet Cutting List Generator");
  lines.push("");
  
  return lines.join("\n");
}
